/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Interfaces.ControllerInterface;
import Interfaces.CountryInterface;
import java.awt.CardLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author priva_000
 */
public class AirportPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form AirportPanel
     */
    public AirportPanel() {
        initComponents();

        GameController.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeadline = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        airportLayoutPanel = new javax.swing.JPanel();
        checkinPanel = new javax.swing.JPanel();
        btnGo = new javax.swing.JButton();
        lblInventory = new javax.swing.JLabel();
        cbHighFriend = new javax.swing.JCheckBox();
        cbGun = new javax.swing.JCheckBox();
        ddlCountries = new javax.swing.JComboBox();
        lblSelect = new javax.swing.JLabel();
        lblYouAre = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        flyingPanel = new javax.swing.JPanel();
        lblFlying = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblHeadline.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeadline.setText("Airport");

        airportLayoutPanel.setLayout(new java.awt.CardLayout());

        btnGo.setText("Travel ");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        lblInventory.setText("Help items");

        cbHighFriend.setText("High friend ($500)");

        cbGun.setText("Gun ($1500)");

        lblSelect.setText("Select country:");

        lblYouAre.setText("You are traveling from");

        lblCountry.setText("{country}");

        javax.swing.GroupLayout checkinPanelLayout = new javax.swing.GroupLayout(checkinPanel);
        checkinPanel.setLayout(checkinPanelLayout);
        checkinPanelLayout.setHorizontalGroup(
            checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinPanelLayout.createSequentialGroup()
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGo)
                    .addGroup(checkinPanelLayout.createSequentialGroup()
                        .addComponent(lblSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkinPanelLayout.createSequentialGroup()
                        .addComponent(lblYouAre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountry))
                    .addGroup(checkinPanelLayout.createSequentialGroup()
                        .addComponent(lblInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbHighFriend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGun)))
                .addGap(0, 494, Short.MAX_VALUE))
        );
        checkinPanelLayout.setVerticalGroup(
            checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinPanelLayout.createSequentialGroup()
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYouAre)
                    .addComponent(lblCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelect)
                    .addComponent(ddlCountries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventory)
                    .addComponent(cbHighFriend)
                    .addComponent(cbGun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGo)
                .addGap(0, 264, Short.MAX_VALUE))
        );

        airportLayoutPanel.add(checkinPanel, "checkinCard");

        lblFlying.setText("You are flying..");
        flyingPanel.add(lblFlying);

        airportLayoutPanel.add(flyingPanel, "flyingCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeadline)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(airportLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeadline)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airportLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        changeCard("checkinCard");
    }//GEN-LAST:event_formComponentShown

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        GameController controller = GameController.getInstance();

        CountryInterface country = (CountryInterface) ddlCountries.getSelectedItem();

        boolean isSuccessful = controller.getService().fly(country);

        if (!isSuccessful) {
            JOptionPane.showMessageDialog(this, "Could not fly you to the destination " + country.getName());
            return;
        }

        changeCard("flyingCard");

        controller.requestUpdate();
    }//GEN-LAST:event_btnGoActionPerformed

    private void changeCard(String cardName) {
        CardLayout layout = (CardLayout) this.airportLayoutPanel.getLayout();
        layout.show(this.airportLayoutPanel, cardName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel airportLayoutPanel;
    private javax.swing.JButton btnGo;
    private javax.swing.JCheckBox cbGun;
    private javax.swing.JCheckBox cbHighFriend;
    private javax.swing.JPanel checkinPanel;
    private javax.swing.JComboBox ddlCountries;
    private javax.swing.JPanel flyingPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblFlying;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblYouAre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        GameController controller = GameController.getInstance();
        ControllerInterface service = controller.getService();
        CountryInterface currentCountry = service.getPlayer().getCurrentCountry();

        lblCountry.setText(currentCountry.getName());

        ddlCountries.removeAllItems();
        for (CountryInterface country : service.getCountries()) {
            if (currentCountry.equals(country)) {
                continue;
            }

            ddlCountries.addItem(country);
        }
    }
}
