/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Interfaces.PlayerInterface;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import java.util.Map.Entry;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author priva_000
 */
public class GamePanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();

        GameController.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        lblPlayerName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblCurrentCountry = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblNumberOfDays = new javax.swing.JLabel();
        lblHealthState = new javax.swing.JLabel();
        lblHealth = new javax.swing.JLabel();
        lblBalanceState = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblInventory = new javax.swing.JLabel();
        playerMenuPanel = new javax.swing.JPanel();
        btnAirport = new javax.swing.JButton();
        btnMarketplace = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        inventoryListPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        marketplacePanel = new Presentation.MarketplacePanel();
        airportPanel = new Presentation.AirportPanel();
        hospitalPanel = new Presentation.HospitalPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblPlayerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPlayerName.setText("{playerName}");

        lblCountry.setText("Country:");

        lblCurrentCountry.setText("{country}");

        lblDay.setText("Day:");

        lblNumberOfDays.setText("{day}");

        lblHealthState.setText("{healthState}");

        lblHealth.setText("Health:");

        lblBalanceState.setText("{balance}");

        lblBalance.setText("Balance:");

        lblInventory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInventory.setText("Inventory");

        playerMenuPanel.setLayout(new java.awt.BorderLayout());

        btnAirport.setText("Airport");
        btnAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirportActionPerformed(evt);
            }
        });
        playerMenuPanel.add(btnAirport, java.awt.BorderLayout.PAGE_START);

        btnMarketplace.setText("Marketplace");
        btnMarketplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarketplaceActionPerformed(evt);
            }
        });
        playerMenuPanel.add(btnMarketplace, java.awt.BorderLayout.CENTER);

        btnHospital.setText("Hospital");
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });
        playerMenuPanel.add(btnHospital, java.awt.BorderLayout.PAGE_END);

        inventoryListPanel.setBackground(new java.awt.Color(204, 153, 0));
        inventoryListPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalanceState)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayerName)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblCountry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrentCountry))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumberOfDays))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHealthState))
                    .addComponent(lblInventory))
                .addGap(0, 164, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addComponent(lblPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(lblCurrentCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDay)
                    .addComponent(lblNumberOfDays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealth)
                    .addComponent(lblHealthState))
                .addGap(7, 7, 7)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(lblBalanceState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(51, 204, 0));
        contentPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        contentPanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(marketplacePanel, "marketplaceCard");
        contentPanel.add(airportPanel, "airportCard");
        contentPanel.add(hospitalPanel, "hospitalCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarketplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarketplaceActionPerformed
        changeContentCard("marketplaceCard");
    }//GEN-LAST:event_btnMarketplaceActionPerformed

    private void btnAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirportActionPerformed
        changeContentCard("airportCard");
    }//GEN-LAST:event_btnAirportActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        changeContentCard("hospitalCard");
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void changeContentCard(String cardName) {
        CardLayout manager = (CardLayout) contentPanel.getLayout();
        manager.show(contentPanel, cardName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Presentation.AirportPanel airportPanel;
    private javax.swing.JButton btnAirport;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnMarketplace;
    private javax.swing.JPanel contentPanel;
    private Presentation.HospitalPanel hospitalPanel;
    private javax.swing.JPanel inventoryListPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceState;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCurrentCountry;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealthState;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblNumberOfDays;
    private javax.swing.JLabel lblPlayerName;
    private Presentation.MarketplacePanel marketplacePanel;
    private javax.swing.JPanel playerMenuPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        GameController controller = GameController.getInstance();
        PlayerInterface player = controller.getService().getPlayer();

        lblPlayerName.setText(player.getName());
        lblCurrentCountry.setText(player.getCurrentCountry().getName());
        lblNumberOfDays.setText("#" + controller.getService().getElapsedDays());
        lblHealthState.setText(player.getLife() + "%");
        lblBalanceState.setText("$" + player.getBalance());

        revalidateInventoryList(player);
    }

    private void revalidateInventoryList(PlayerInterface player) {
        List<Entry<String, Integer>> inventoryDrugs = new LinkedList<>();
        for (Entry<String, Integer> entry : player.getDrugs().entrySet()) {
            if (entry.getValue() > 0) {
                inventoryDrugs.add(entry);
            }
        }

        inventoryListPanel.removeAll();

        if (inventoryDrugs.size() > 0) {
            JList drugs = new JList(inventoryDrugs.toArray());
            drugs.setOpaque(false);
            drugs.setCellRenderer(new InventoryItemRenderer());
            JScrollPane drugPanel = new JScrollPane(drugs);

            inventoryListPanel.add(drugPanel);
        } else {
            JLabel lbl = new JLabel("Your inventory is empty");
            lbl.setForeground(Color.lightGray);
            lbl.setHorizontalAlignment(SwingConstants.CENTER);

            JScrollPane drugPanel = new JScrollPane(lbl);
            inventoryListPanel.add(drugPanel);

        }
        inventoryListPanel.revalidate();
    }
}
