/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Interfaces.ControllerInterface;
import Interfaces.CountryInterface;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author priva_000
 */
public class HospitalPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form AirportPanel
     */
    public HospitalPanel() {
        initComponents();

        lblResult.setVisible(false);

        GameController.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeadline = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHealth = new javax.swing.JLabel();
        lblHealthState = new javax.swing.JLabel();
        lblPriceDescription = new javax.swing.JLabel();
        btnPurchaseLife = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblHeadline.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeadline.setText("Hospital");

        lblHealth.setText("You current health is");

        lblHealthState.setText("{health}");

        lblPriceDescription.setText("When purchasing health it will cost you 25% of your current balance");

        btnPurchaseLife.setText("Purchase health");
        btnPurchaseLife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseLifeActionPerformed(evt);
            }
        });

        lblResult.setText("{result}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadline)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHealthState))
                    .addComponent(lblPriceDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPurchaseLife)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResult)))
                .addGap(0, 261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeadline)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealth)
                    .addComponent(lblHealthState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPurchaseLife)
                    .addComponent(lblResult))
                .addGap(0, 302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        lblResult.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void btnPurchaseLifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseLifeActionPerformed
        GameController controller = GameController.getInstance();

        // Give life to player
        boolean isSuccessful = controller.getService().vistHospital(controller.getService().getPlayer());

        String strResultText = isSuccessful
                ? "You have gain full life agian"
                : "Could not give you any life, do you really need life?";

        lblResult.setVisible(true);
        lblResult.setText(strResultText);

        controller.requestUpdate();
    }//GEN-LAST:event_btnPurchaseLifeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchaseLife;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealthState;
    private javax.swing.JLabel lblPriceDescription;
    private javax.swing.JLabel lblResult;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        GameController controller = GameController.getInstance();
        ControllerInterface service = controller.getService();

        String strLife = Integer.toString(service.getPlayer().getLife());
        lblHealthState.setText(strLife + "%");
    }
}
