/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.awt.CardLayout;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author priva_000
 */
public class MainFrame extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        MainViewState.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stagePanel = new javax.swing.JPanel();
        startPanel = new Presentation.StartPanel();
        gamePanel = new Presentation.GamePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 530));

        stagePanel.setLayout(new java.awt.CardLayout());
        stagePanel.add(startPanel, "startCard");
        stagePanel.add(gamePanel, "gameCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Presentation.GamePanel gamePanel;
    private javax.swing.JPanel stagePanel;
    private Presentation.StartPanel startPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        String stateName = (String) o1;

        switch (stateName) {
            case "main":
                changeContentCard("startCard");
                break;
            case "playing":
                changeContentCard("gameCard");
                break;
        }
    }

    private void changeContentCard(String cardName) {
        CardLayout manager = (CardLayout) stagePanel.getLayout();
        manager.show(stagePanel, cardName);
    }
}
