/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Interfaces.DrugInterface;
import Interfaces.MarketplaceInterface;
import Interfaces.PlayerInterface;
import javax.swing.JOptionPane;

/**
 *
 * @author priva_000
 */
public class MarketplaceItem extends javax.swing.JPanel {

    private DrugInterface drug;
    private MarketplaceInterface marketplace;

    /**
     * Creates new form MarketplaceItem
     */
    public MarketplaceItem() {
        initComponents();
    }

    public void setData(MarketplaceInterface marketplace, DrugInterface drug) {
        GameController controller = GameController.getInstance();
        PlayerInterface player = controller.getService().getPlayer();

        this.drug = drug;
        this.marketplace = marketplace;

        this.lblDrugName.setText(drug.getName());

        String strPrice = Integer.toString(drug.getPrice());
        this.lblPrice.setText("$" + strPrice);

        String strAmount = Integer.toString(drug.getAvailability());
        
        this.lblAmount.setText(strAmount + "kg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrice = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        btnSell = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();

        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrice.setText("{price}");
        lblPrice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblDrugName.setText("{drugName}");

        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAmount.setText("{amount}");
        lblAmount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrugName, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(183, 183, 183)
                .addComponent(lblPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPurchase)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblAmount)
                .addComponent(lblPrice))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        GameController controller = GameController.getInstance();

        boolean isPurchased = marketplace.sell(this.drug.getName(), 1, controller.getService().getPlayer());

        if (!isPurchased) {
            JOptionPane.showMessageDialog(this, "Could not sell " + this.drug.getName());
            return;
        }

        controller.requestUpdate();
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        GameController controller = GameController.getInstance();

        boolean isPurchased = marketplace.buy(this.drug.getName(), 1, controller.getService().getPlayer());

        if (!isPurchased) {
            JOptionPane.showMessageDialog(this, "Could not purchase " + this.drug.getName());
            return;
        }
        controller.requestUpdate();
    }//GEN-LAST:event_btnPurchaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblPrice;
    // End of variables declaration//GEN-END:variables
}
