/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Interfaces.ControllerInterface;
import static Presentation.GameController.getInstance;
import javax.swing.JOptionPane;

/**
 *
 * @author priva_000
 */
public class StartPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeadline = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        gameMenuPanel = new javax.swing.JPanel();
        btnHighscore = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        lblHeadline.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        lblHeadline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeadline.setText("Mafia Game");

        gameMenuPanel.setMinimumSize(new java.awt.Dimension(2147483647, 69));
        gameMenuPanel.setPreferredSize(new java.awt.Dimension(250, 69));
        gameMenuPanel.setLayout(new javax.swing.BoxLayout(gameMenuPanel, javax.swing.BoxLayout.Y_AXIS));

        btnHighscore.setText("Start new game");
        btnHighscore.setMaximumSize(new java.awt.Dimension(250, 23));
        btnHighscore.setMinimumSize(new java.awt.Dimension(250, 23));
        btnHighscore.setPreferredSize(new java.awt.Dimension(250, 23));
        btnHighscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighscoreActionPerformed(evt);
            }
        });
        gameMenuPanel.add(btnHighscore);

        btnStartGame.setText("Highscore");
        btnStartGame.setMargin(new java.awt.Insets(7, 14, 7, 14));
        btnStartGame.setMaximumSize(new java.awt.Dimension(250, 23));
        btnStartGame.setMinimumSize(new java.awt.Dimension(250, 23));
        btnStartGame.setPreferredSize(new java.awt.Dimension(250, 23));
        gameMenuPanel.add(btnStartGame);

        btnExit.setText("Exit");
        btnExit.setMaximumSize(new java.awt.Dimension(250, 23));
        btnExit.setMinimumSize(new java.awt.Dimension(250, 23));
        btnExit.setPreferredSize(new java.awt.Dimension(250, 23));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        gameMenuPanel.add(btnExit);

        contentPanel.add(gameMenuPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadline)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHighscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighscoreActionPerformed
        GameController controller = GameController.getInstance();
        ControllerInterface service = controller.getService();
        
        String playerName = JOptionPane.showInputDialog(this, "What do you want to be called?");
        service.getPlayer().setName(playerName);
        
        MainViewState.getInstance().change("playing");
        controller.requestUpdate();
    }//GEN-LAST:event_btnHighscoreActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHighscore;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel gameMenuPanel;
    private javax.swing.JLabel lblHeadline;
    // End of variables declaration//GEN-END:variables
}
