/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Interfaces.ControllerInterface;
import static Presentation.GameController.getInstance;
import javax.swing.JOptionPane;

/**
 *
 * @author priva_000
 */
public class StartPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameMenuPanel = new javax.swing.JPanel();
        btnHighscore = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblHeadline = new javax.swing.JLabel();

        gameMenuPanel.setLayout(new java.awt.BorderLayout());

        btnHighscore.setText("Start new game");
        btnHighscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighscoreActionPerformed(evt);
            }
        });
        gameMenuPanel.add(btnHighscore, java.awt.BorderLayout.PAGE_START);

        btnStartGame.setText("Highscore");
        gameMenuPanel.add(btnStartGame, java.awt.BorderLayout.CENTER);

        btnExit.setText("Exit");
        gameMenuPanel.add(btnExit, java.awt.BorderLayout.PAGE_END);

        lblHeadline.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeadline.setText("Mafia Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeadline)
                        .addGap(0, 199, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadline)
                .addGap(49, 49, 49)
                .addComponent(gameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHighscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighscoreActionPerformed
        GameController controller = GameController.getInstance();
        ControllerInterface service = controller.getService();
        
        String playerName = JOptionPane.showInputDialog(this, "What do you want to be called?");
        service.getPlayer().setName(playerName);
        
        MainViewState.getInstance().change("playing");
        controller.requestUpdate();
    }//GEN-LAST:event_btnHighscoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHighscore;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JPanel gameMenuPanel;
    private javax.swing.JLabel lblHeadline;
    // End of variables declaration//GEN-END:variables
}
